networks:
  project:
    driver: bridge
services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - project
  
  frontend:
    container_name: client
    image: ghcr.io/seaz96/gost_project-frontend:main
    volumes:
      - ./src:/app/src
    ports:
      - "80"
    networks:
      - project
    environment:
      API_URL: https://gost-storage.ru/api/
  
  backend:
    container_name: server
    image: ghcr.io/seaz96/gost_project-backend:main
    ports:
      - "8080:8080"
    networks:
      - project
    depends_on:
      - db
    environment:
      DATABASE_HOST: postgres_db
      DATABASE_PASSWORD: password
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PORT: 5432
      MINIO_PUBLIC_KEY: admin
      MINIO_PRIVATE_KEY: password
      MINIO_BUCKET: document
      MINIO_HOST: minio
      MINIO_PORT: 9000
      ELASTIC_PASSWORD: password
      ELASTIC_INDEX: index_name
      ELASTIC_HOST: host_name
      ORIGINS: http://localhost:3000|https://gost-storage.ru|https://test.gost-storage.ru
  
  db:
    container_name: postgres_db
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - project
    volumes:
      - db-data:/var/lib/postgresql/data

  minio:
    container_name: minio
    image: bitnami/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - project
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DEFAULT_BUCKETS=document
  elasticsearch:
    image: public.ecr.aws/elastic/elasticsearch:8.13.4
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS = -Xms1g -Xmx1g
      - MAX_LOCKED_MEMORY = 100000
      - ES_HEAP_SIZE = 128m
      - ELASTIC_USERNAME= elastic
      - ELASTIC_PASSWORD= password
      - xpack.security.enrollment.enabled=true
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    networks:
      - project
  kibana:
    container_name: kibana
    image: public.ecr.aws/elastic/kibana:8.13.4
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - project
    ports:
      - "5601:5601"
volumes:
  db-data:
  minio_data:
    driver: local
  elastic-data:
    driver: local
