export type GostToSave = {
    "designation": string,
    "fullName": string,
    "codeOKS": string,
    "activityField": string,
    "acceptanceDate": string,
    "commissionDate": string,
    "author": string,
    "acceptedFirstTimeOrReplaced": string,
    "content": string,
    "keyWords": string,
    "keyPhrases": string,
    "applicationArea": string,
    "adoptionLevel": number,
    "documentText": string,
    "changes": string,
    "amendments": string,
    "status": number,
    "harmonization": number,
    "isPrimary": true,
    "referencesId": number[]
}